MIPS: Simplify FP context access
This patch replaces the fpureg_t typedef with a "union fpureg" enabling
easier access to 32 & 64 bit values. This allows the access macros used
in cp1emu.c to be simplified somewhat. It will also make it easier to
expand the width of the FP registers as will be done in a future
patch in order to support the 128 bit registers introduced with MSA.

No behavioural change is intended by this patch.

[ralf@linux-mips.org: Fixed build error affecting 64 bit platforms:
  CC      arch/mips/math-emu/cp1emu.o
arch/mips/math-emu/cp1emu.c: In function ‘fpu_emu’:
arch/mips/math-emu/cp1emu.c:1974:4: warning: passing argument 1 of ‘ieee754sp_flong’ makes integer from pointer without a cast [enabled by default]
In file included from arch/mips/math-emu/cp1emu.c:52:0:
arch/mips/math-emu/ieee754.h:123:11: note: expected ‘s64’ but argument is of type ‘__u32 *’
arch/mips/math-emu/cp1emu.c:1979:4: error: incompatible type for argument 1 of ‘ieee754dp_flong’
In file included from arch/mips/math-emu/cp1emu.c:52:0:
arch/mips/math-emu/ieee754.h:170:11: note: expected ‘s64’ but argument is of type ‘union fpureg’
make[1]: *** [arch/mips/math-emu/cp1emu.o] Error 1
make: *** [arch/mips/math-emu/cp1emu.o] Error 2]

Signed-off-by: Paul Burton <paul.burton@imgtec.com>
Reviewed-by: Qais Yousef <qais.yousef@imgtec.com>
Cc: linux-mips@linux-mips.org
Patchwork: https://patchwork.linux-mips.org/patch/6420/
Signed-off-by: Ralf Baechle <ralf@linux-mips.org>