CHROMIUM: drm: msm: Mark as BROKEN
Build fails with

drivers/gpu/drm/msm/mdp/mdp4/mdp4_plane.c: In function 'mdp4_plane_prepare_fb':
drivers/gpu/drm/msm/mdp/mdp4/mdp4_plane.c:109:2: error:
	implicit declaration of function 'msm_framebuffer_prepare'
drivers/gpu/drm/msm/mdp/mdp4/mdp4_plane.c: In function 'mdp4_plane_cleanup_fb':
drivers/gpu/drm/msm/mdp/mdp4/mdp4_plane.c:120:2: error:
	implicit declaration of function 'msm_framebuffer_cleanup'

and various other errors. Analysis suggests bad/incomplete back-ports.

Fixes: e5108fbae4a8 ("BACKPORT: drm: Pass in new and old plane state to prepare_fb and cleanup_fb")
Fixes: 4ffb7351f4a8 ("drm/plane: Pass old state to ->atomic_update()")
BUG=chromium:583462
TEST=None (build)

Change-Id: Ic4acc364d52467cf575b3421f5b4dcf0f904f7d6
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325484
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>