UPSTREAM: of: Fix of_graph_parse_endpoint stub for !CONFIG_OF builds
This patch fixes the following build error:

   In file included from drivers/media/i2c/adv7343.c:29:0:
>> include/linux/of_graph.h:41:1: error: expected identifier or '(' before '{' token
    {
    ^
   include/linux/of_graph.h:39:19: warning: 'of_graph_parse_endpoint' declared 'static' but never defined [-Wunused-function]
    static inline int of_graph_parse_endpoint(const struct device_node *node,
                      ^

vim +41 include/linux/of_graph.h

    35                                          const struct device_node *node);
    36  struct device_node *of_graph_get_remote_port(const struct device_node *node);
    37  #else
    38
    39  static inline int of_graph_parse_endpoint(const struct device_node *node,
    40                                          struct of_endpoint *endpoint);
  > 41  {
    42          return -ENOSYS;
    43  }
    44

BUG=chromium:393773
TEST=Built chromeos-3.14 kernel, make sure we still boot (to the point where
we look for a root device).

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
(cherry picked from commit 00fd9619120db1d6a19be2f9e3df6f76234b311b)

Change-Id: Ibe4b32125ac284cc13338993521a4e6b5f26d7f7
Signed-off-by: Rhyland Klein <rklein@nvidia.com>
Reviewed-on: https://chromium-review.googlesource.com/208184
Tested-by: Andrew Chew <achew@nvidia.com>
Reviewed-by: Olof Johansson <olofj@chromium.org>
Commit-Queue: Andrew Chew <achew@nvidia.com>