um: use asm-generic/scatterlist.h
commit ff35bd54456e18878c361a8a2deeb41c9688458f
(lib/scatterlist: make ARCH_HAS_SG_CHAIN an actual Kconfig) changed
some architectures to use the generic scatterlist.h but this broke
um:

In file included from init/main.c:75:0:
include/linux/blkdev.h:25:29: fatal error: asm/scatterlist.h:
        No such file or directory

Make um use the generic scatterlist.h as well

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Cc: kbuild test robot <fengguang.wu@intel.com>
Cc: Jeff Dike <jdike@addtoit.com>
Cc: Richard Weinberger <richard@nod.at>
Signed-off-by: Laura Abbott <lauraa@codeaurora.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>