UPSTREAM: x86/apic: Fix the devicetree build in certain configs
Without this patch:

  LD      init/built-in.o
  arch/x86/built-in.o: In function `dtb_lapic_setup': kernel/devicetree.c:155:
  undefined reference to `apic_force_enable'
  Makefile:923: recipe for target 'vmlinux' failed
  make: *** [vmlinux] Error 1

BUG=chrome-os-partner:39522
TEST=With entire series applied, boot on strago and check if
/sys/kernel/debug/pinctrl/INT33FF0[0-3]/pins lists pins.

Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>
Reviewed-by: Maciej W. Rozycki <macro@linux-mips.org>
Cc: David Rientjes <rientjes@google.com>
Cc: Jan Beulich <JBeulich@suse.com>
Link: http://lkml.kernel.org/r/1422905231-16067-1-git-send-email-ricardo.ribalda@gmail.com
Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from commit b273c2c2f2d2d13dc0bfa8923d52fbaf8fa56ae8)
Signed-off-by: Dhinakaran Pandiyan <dhinakaran.pandiyan@intel.com>

Change-Id: Iad376d3df701069c2f69f7fb17cc4fdfdf7a4155
Reviewed-on: https://chromium-review.googlesource.com/269230
Reviewed-by: Eric Caruso <ejcaruso@chromium.org>
Commit-Queue: Dhinakaran Pandiyan <dhinakaran.pandiyan@intel.com>
Tested-by: Dhinakaran Pandiyan <dhinakaran.pandiyan@intel.com>