CHROMIUM: trusty: Fix building as module
trusty is marked tristate and should therefore be buildable
as module. However, that fails with

drivers/trusty/trusty.c:74:5: error: redefinition of 'trusty_fast_call32'
 s32 trusty_fast_call32(struct device *dev, u32 smcnr, u32 a0, u32 a1, u32 a2)
      ^
In file included from drivers/trusty/trusty.c:25:0:
include/linux/trusty/trusty.h:35:19: note:
	previous definition of 'trusty_fast_call32' was here

drivers/trusty/trusty.c:160:5: error: redefinition of 'trusty_std_call32'
s32 trusty_std_call32(struct device *dev, u32 smcnr, u32 a0, u32 a1, u32 a2)

In file included from drivers/trusty/trusty.c:25:0:
include/linux/trusty/trusty.h:30:19: note:
	previous definition of 'trusty_std_call32' was here

Fixes: 3dcb2dea37f2 (" ANDROID: trusty: Add trusty driver")
BUG=chromium:583462
TEST=None (build)

Change-Id: Ib88915ac4a83b88cf4371447ea120cab08e93998
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325477
Reviewed-by: Dylan Reid <dgreid@chromium.org>