powerpc: include asm/dma.h explicitly
commit ff35bd54456e18878c361a8a2deeb41c9688458f (lib/scatterlist: make
ARCH_HAS_SG_CHAIN an actual Kconfig) changed powerpc to use the generic
scatterlist.h.  The powerpc scatterlist.h header was including asm/dma.h
as well so removing the include broke a few things:

arch/powerpc/platforms/52xx/efika.c: In function 'efika_probe':
arch/powerpc/platforms/52xx/efika.c:210:2: error: 'ISA_DMA_THRESHOLD' undeclared
arch/powerpc/platforms/52xx/efika.c:211:2: error: 'DMA_MODE_READ' undeclared
arch/powerpc/platforms/52xx/efika.c:212:2: error: 'DMA_MODE_WRITE' undeclared

Explicitly include asm/dma.h where necessary.

Signed-off-by: Laura Abbott <lauraa@codeaurora.org>
Reported-by: kbuild test robot <fengguang.wu@intel.com>
Cc: kbuild test robot <fengguang.wu@intel.com>
Cc: Benjamin Herrenschmidt <benh@kernel.crashing.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>