metag: move EXPORT_SYMBOLs in libs to metag_ksyms.c
Move all EXPORT_SYMBOLs in libs-y directories (arch/metag/{lib,tbx})
into metag_ksyms.c so that they don't get omitted by the static linker
if they're not used by any other statically linked code, which can
result in undefined symbols when building modules.

For example a randconfig caused the following error:
ERROR: "csum_partial" [fs/reiserfs/reiserfs.ko] undefined!

Signed-off-by: James Hogan <james.hogan@imgtec.com>
Cc: Rusty Russell <rusty@rustcorp.com.au>