UPSTREAM: ASoC: Intel: Skylake: Fix null ptr dereferenced in skl_tplg_bind_sinks
This patch fixes the below warning form smatch and makes the
skl_tplg_bind_sinks take the next sink as argument which is true
when the current sink is valid

sound/soc/intel/skylake/skl-topology.c:453 skl_tplg_bind_sinks()
	error: we previously assumed 'sink' could be null (see line 452)

sound/soc/intel/skylake/skl-topology.c
   451
   452		if (!sink)
                     ^^^^
New check.  Reversed?

   453			return skl_tplg_bind_sinks(sink, skl, src_mconfig);
                                                   ^^^^ This is
dereferenced inside the function.

   454
   455		return 0;

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Jeeja KP <jeeja.kp@intel.com>
Signed-off-by: Vinod Koul <vinod.koul@intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 0ed95d769c8d6c1030dd9f94cf6fb2a6ed98a4ce)
Link: git://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git
br: for-next
Signed-off-by: Radhakrishna Sripada <radhakrishna.sripada@intel.com>

BUG=chrome-os-partner:41280
TEST=with the whole series applied, audio works on SKL.
TEST=there are no regressions observed on BSW.

Change-Id: I0278dbd86e9547a0f9bf3c254c756522daff10cb
Reviewed-on: https://chromium-review.googlesource.com/312257
Commit-Ready: James Ausmus <james.ausmus@intel.com>
Tested-by: Vedang Patel <vedang.patel@intel.com>
Reviewed-by: Derek Basehore <dbasehore@chromium.org>