UPSTREAM: ASoC: Export devm_snd_soc_register_platform()
devm_snd_soc_register_platform() is used in drivers which can be build as
modules, so it needs to be exported to avoid linkers errors like:

	ERROR: "devm_snd_soc_register_platform" [sound/soc/omap/snd-soc-omap.ko] undefined!
	ERROR: "devm_snd_soc_register_platform" [sound/soc/davinci/snd-soc-davinci.ko] undefined!

Fixes: 8931bf620 ("ASoC: Add resource managed snd_soc_register_platform()")
Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
Signed-off-by: Mark Brown <broonie@linaro.org>
(cherry picked from commit 1f23380b803a670a9eb53f63fd0c662d20ab1b66)
Signed-off-by: Kevin Strasser <kevin.strasser@intel.com>

BUG=chrome-os-partner:29649
TEST=With entire patch series applied, audio playback is working

Change-Id: I5f0de4993f86a95d243c7efb738a455e83b76941
Reviewed-on: https://chromium-review.googlesource.com/215232
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Commit-Queue: Ben Zhang <benzh@chromium.org>
Tested-by: Ben Zhang <benzh@chromium.org>