CHROMIUM: tegra: Update powergate API function calls
Commit 10383e6b73c3 ("CHROMIUM: soc/tegra: pmc: Add dependency for power
partition") Changed the tegra powergate API but missed two function calls.
This results in the following build error.

drivers/ata/ahci_tegra.c: In function 'tegra_ahci_power_off':
drivers/ata/ahci_tegra.c:164:2: error:
	implicit declaration of function 'tegra_powergate_power_off'

Fixes: 10383e6b73c3 ("CHROMIUM: soc/tegra: pmc: Add dependency for power partition")
BUG=chromium:583462
TEST=None (build)

Change-Id: I4b79afc75d48a12998bbcfa1c8be19bb7de0fd8a
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325475
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>