UPSTREAM: ASoC: Intel: Fix build with CONFIG_SLEEP enabled.
Fix the following build error when CONFIG_SLEEP is enabled and CONFIG_RUNTIME
is disabled. The BDW ADSP sleep PM functionality depends on the runtime pm
calls for context save/restore.

All error/warnings:

>> ERROR: "snd_soc_suspend" undefined!
>> ERROR: "snd_soc_resume" undefined!

Reported-by: kbuild test robot <fengguang.wu@intel.com>
Signed-off-by: Liam Girdwood <liam.r.girdwood@linux.intel.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 7b8ef67a0b1edb37957a2aa71a5c0bbbcf2694e9)
BUG=chrome-os-partner:40036
TEST=Audio playback works on test device

Change-Id: Id3a2aa21c1003d744d8ae10f0220046496e6b528
Reviewed-on: https://chromium-review.googlesource.com/270887
Reviewed-by: Dylan Reid <dgreid@chromium.org>
Commit-Queue: Bernie Thompson <bhthompson@chromium.org>
Tested-by: Bernie Thompson <bhthompson@chromium.org>