move is_hugepage_active() outside #ifdef CONFIG_MEMORY_FAILURE
This patch fixes the following build error:

  tree:   git://git.cmpxchg.org/linux-mmotm.git master
  head:   1cd1467d27f0fdcc21c34581ab91ed29ead81621
  commit: 12e2508d0cb3168251a0dacdd92fd4cf991ca654 [157/412] mm: memory-hotplug: enable memory hotplug to handle hugepage
  config: x86_64-randconfig-c06-0815 (attached as .config)

  All error/warnings:

     mm/built-in.o: In function `__offline_pages.constprop.33':
  >> memory_hotplug.c:(.ref.text+0x52f): undefined reference to `is_hugepage_active'

This should be merged with the following commit in the same tree:

  commit 12e2508d0cb3168251a0dacdd92fd4cf991ca654
  Author: Naoya Horiguchi <n-horiguchi@ah.jp.nec.com>
  Date:   Fri Aug 16 00:06:33 2013 +0000

      mm: memory-hotplug: enable memory hotplug to handle hugepage

Signed-off-by: Naoya Horiguchi <n-horiguchi@ah.jp.nec.com>
Reported-by: Wu Fengguang <fengguang.wu@intel.com>
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>