CHROMIUM: gpu: exynos_drm: Fix exynos_drm_crtc_finish_pageflip function declaration
Build fails with

drivers/gpu/drm/exynos/exynos_drm_crtc.c:420:6: error:
	conflicting types for 'exynos_drm_crtc_finish_pageflip'

because exynos_drm_crtc_finish_pageflip is declared differently in the source
and include file. The declaration in the include file was changed with commit
27ebc6d4d34a6 ("BACKPORT: drm/irq: Use unsigned int pipe in public API"), but
the source file was not changed accordingly.

Fixes: 27ebc6d4d34a6 ("BACKPORT: drm/irq: Use unsigned int pipe in public API")
BUG=chromium:583462
TEST=None (build)

Change-Id: I67b80619fcd818b4b64c6eacd218502f41b79515
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325306
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>