CHROMIUM: net: wireless: bcmdhd: add missing linux/ctype.h include
Using tolower() without including results in:

drivers/net/wireless/bcmdhd/bcmwifi_channels.c: In function 'wf_chspec_aton':
drivers/net/wireless/bcmdhd/bcmwifi_channels.c:353:2: error:
	implicit declaration of function 'tolower'

Fixes: 8aea3c8cac08 ("CHROMIUM: net: wireless: bcmdhd: Remove defines")
BUG=chromium:583462
TEST=None (build)

Change-Id: Idcd5fafb5f2d372d79192c19def10efc9f3d5a8c
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325398
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>