Revert "UPSTREAM: ALSA: hda - Create jack-detection kcontrols"
This reverts commit 9de698b86b5a65cabab5b168336a7ec105b20ce0

The x86/amd64 kernel builds are broken:

ERROR: "snd_hda_jack_add_kctl" [sound/pci/hda/snd-hda-codec-hdmi.ko] undefined

http://build.chromium.org/p/chromiumos/builders/amd64%20generic%20full/builds/2165/steps/cbuildbot/logs/stdio
Change-Id: I4fe1f631c0e784565a9a0abb72ab226bc0e8483d
Reviewed-on: https://gerrit.chromium.org/gerrit/21315
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>