UPSTREAM: ath10k: fix build error when hwmon is off
kbuild reported a linking error:

ERROR: "devm_hwmon_device_register_with_groups"
[drivers/net/wireless-3.18/ath/ath10k/ath10k_core.ko] undefined!

Fix it by returning early and letting the compiler to optimise out the function
call.

Signed-off-by: Kalle Valo <kvalo@qca.qualcomm.com>
(cherry picked from commit 96bba98393f97e4c4bfe29341b3ad2adef32bde2)
(source: https://github.com/kvalo/ath/tree/ath-qca)

BUG=chrome-os-partner:35262
TEST=build/boot on storm suceeded. Setup Storm board as AP using hostapd and
connected to the board using another device. Device was able to connect to
the internet and load multiple websites.

Change-Id: Id4e07a7c86f94a85b3b84885d5132b96b31f7209
Signed-off-by: Mathieu Olivari <mathieu@codeaurora.org>
Reviewed-on: https://chromium-review.googlesource.com/241676
Reviewed-by: Toshi Kikuchi <toshik@chromium.org>
Tested-by: Toshi Kikuchi <toshik@chromium.org>