CHROMIUM: ASoC: tegra210_iqc: Fix typo
Build fails with:

sound/soc/tegra-alt/tegra210_iqc_alt.c:311:18: error:
tegra210_iqc_reg_defaults undeclared here (not in a function)
  .reg_defaults = tegra210_iqc_reg_defaults,

Fixes: 7ec159b67ea47 ("CHROMIUM: Add audio drivers for NVidia T210")
BUG=chromium:583462
TEST=None (build)

Change-Id: I9e3f40e2b2635e055f9926d16770591d5e5a5f87
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325308
Reviewed-by: Anatol Pomazau <anatol@google.com>