CHROMIUM: mm: memcontrol: Remove unused drain_all_stock_sync
This causes build failures.

mm/memcontrol.c:2362:13: error: 'drain_all_stock_sync' defined but not used

Breakage seems to have been introduced by the backport of commit
"UPSTREAM: mm: memcontrol: continue cache reclaim from offlined groups",
likely due to missing dependency that cleaned this up before/after said
patch. Remove it now.

BUG=chromium:583462
TEST=None (build)

Change-Id: I5e7595ba6349b0b00c5a06f417fc94ebd1391386
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325388
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>