UPSTREAM: net: cdc_ncm: fix 64bit division build error
The upper timer_interval limit is arbitrary and much higher
than anything usable in the real world.  Reducing it from 15s
to ~4s to make the timer_interval fit in an u32 does not make
much difference.  The limit is still outside the practical
bounds.

This eliminates the need for a 64bit timer_interval, fixing a
build error related to 64bit division:

 drivers/built-in.o: In function `cdc_ncm_get_coalesce':
 ak8975.c:(.text+0x1ac994): undefined reference to `__aeabi_uldivmod'

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Bjørn Mork <bjorn@mork.no>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 7d10d2610cc02d432168ca0c5d964cd9e85c1b06)
Signed-off-by: Ben Chan <benchan@chromium.org>

BUG=chromium:419242
TEST=`USE=mbim emerge-$BOARD chromeos-kernel-3_14`
TEST=Run network3g tests on DUTs with a MBIM modem.

Change-Id: I85dbf54f17d3705c3e45d8c3cde1262ef4450ecc
Reviewed-on: https://chromium-review.googlesource.com/220824
Reviewed-by: Olof Johansson <olofj@chromium.org>
Commit-Queue: Ben Chan <benchan@chromium.org>
Tested-by: Ben Chan <benchan@chromium.org>