CHROMIUM: trusty: Limit to ARM and ARM64
Build on x86 fails with

drivers/trusty/trusty.c:15:26: fatal error:
	asm/compiler.h: No such file or directory

Using linux/compiler.h doesn't help since the code uses arm specific assembler
mnemonics.

Fixes: 3dcb2dea37f2 ("ANDROID: trusty: Add trusty driver")
BUG=chromium:583462
TEST=None (build)

Change-Id: I2d4e36a83dd004bfe17ee00d7517d7f1916a0908
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325502
Reviewed-by: Dylan Reid <dgreid@chromium.org>