include: remove needless instances of <linux/init.h>
In removing __cpuinit and __devinit support, some files will
no longer need to include <linux/init.h>.  Here we audit the
include files themselves, looking for cases where init.h is
sourced but not actually used.  With these cleaned up, we'll
know that the odds of C files implicitly getting init.h from
random headers in here are somewhat reduced.

Some files were getting other headers via init.h, such as:

In file included from fs/cifs/winucase.c:32:0:
include/linux/nls.h:16:1: error: unknown type name ‘u16’

and so their includes were adjusted to reflect what they
were actually requiring.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>