CHROMIUM: sound: hda: Fix bad back-port
Commits 973f0594540b1 ("UPSTREAM: ALSA: hda - Handle error from get_response bus
ops directly") and e64a7d164133e ("BACKPORT: ALSA: hda - fix number of devices
query on hotplug") back-port and fix get_num_devices(). While doing so, reading
the actual number of devices got lost. This results in the following build
error.

sound/pci/hda/hda_codec.c: In function 'snd_hda_get_devices':
sound/pci/hda/hda_codec.c:397:2: error:
	'parm' may be used uninitialized in this function
sound/pci/hda/hda_codec.c:389:15: note: 'parm' was declared here

Fixes: 973f0594540b1 ("UPSTREAM: ALSA: hda - Handle error from get_response bus ops directly")
Fixes: e64a7d164133e ("BACKPORT: ALSA: hda - fix number of devices query on hotplug")
BUG=chromium:583462
TEST=None (build)

Change-Id: If979ef998242245171d452110a47a1b44e963255
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325378
Reviewed-by: Anatol Pomazau <anatol@google.com>