CHROMIUM: nouveau: gm20b: Move gm20b_freq_to_pstate outside CONFIG_THERMAL
Build error:

drivers/gpu/drm/nouveau/nvkm/subdev/clk/gm20b.c:
	In function gm20b_dvfs_predict_millivolts:
drivers/gpu/drm/nouveau/nvkm/subdev/clk/gm20b.c:1865:2: error:
	implicit declaration of function gm20b_freq_to_pstate

if CONFIG_THERMAL is not configured and CONFIG_NOUVEAU_GPU_EDP is configured.

Fixes: ace53840a0f16 ("CHROMIUM: drm/nouveau/clk: gm20b: add gpu edp")
BUG=chromium:583462
TEST=None (build)

Change-Id: I337d348c464ddd042d851d3342c84544f341d8a0
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325347
Reviewed-by: Sean Paul <seanpaul@google.com>