CHROMIUM: gpu: host1x Select PM_DEVFREQ if host1x is configured
Fix build failure.

drivers/gpu/host1x/hw/actmon_hw.c: In function 'actmon_init':
drivers/gpu/host1x/hw/actmon_hw.c:156:36: error:
	'DEVFREQ_WATERMARK_EVENT_BELOW' undeclared
drivers/gpu/host1x/hw/actmon_hw.c:159:36: error:
	'DEVFREQ_WATERMARK_EVENT_ABOVE' undeclared

Fixes: 754716874389 ("gpu: host1x: Add host1x driver")
BUG=chromium:583462
TEST=None (build)

Change-Id: If8d4bd5091aa693939101c6e66c55459409725b2
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325307
Reviewed-by: Sean Paul <seanpaul@google.com>