CHROMIUM: wakeup: Declare constant strings where needed
Strings were declared within CONFIG_PM_DEBUG but used outside of it,
resulting in

kernel/power/main.c:495:31: error: 'automatic' undeclared
kernel/power/main.c:499:31: error: 'unknown' undeclared
kernel/power/main.c:503:31: error: 'user' undeclared
kernel/power/main.c:505:31: error: 'invalid' undeclared

if CONFIG_PM_DEBUG is not configured.

Fixes: e9f06607d891 ("CHROMIUM: wakeup: Clear wakeup_type in userspace")
BUG=chromium:583462
TEST=None (build)

Change-Id: Idbd9b048eec73bf4a566869b6d4f5e1c2a8641e1
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325302
Reviewed-by: Eric Caruso <ejcaruso@chromium.org>