UPSTREAM: ARM: rockchips: ASoC: rockchip: add missing module.h include
Missing module.h in linux directory will cause compile error with randconfig,
like as:
sound/soc/rockchip/rockchip_i2s.c:526:20: error: expected declaration
specifiers or ‘...’ before string constant
MODULE_DESCRIPTION("ROCKCHIP IIS ASoC Interface");

BUG=chrome-os-partner:30167
TEST=Build and boot

Change-Id: I39e5e5ca7b71ed2c4414ed581abd12cc1ff0efa8
Signed-off-by: xujianqun <xjq@rock-chips.com>
Signed-off-by: Mark Brown <broonie@linaro.org>
(cherry picked from git.kernel.org broonie/sound.git for-next
commit 1b21572f8fd791f5b54e5989bc8e0cc5308d2e6c)
Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>
Reviewed-on: https://chromium-review.googlesource.com/209263
Reviewed-by: Doug Anderson <dianders@chromium.org>
Tested-by: Doug Anderson <dianders@chromium.org>
Commit-Queue: Doug Anderson <dianders@chromium.org>