Revert "mm/sl[aou]b: Move kmalloc_node functions to common code"
This reverts commit d9d5aa0bf1c8788f44a7840f5120eee221138f87.

It breaks compilation as follows with CONFIG_DEBUG_KMEMLEAK:

    CC      mm/slub.o
  mm/slub.c:2462:7: error: conflicting types for ‘kmem_cache_alloc_node_trace’
  include/linux/slab.h:313:14: note: previous declaration of ‘kmem_cache_alloc_node_trace’ was here
  mm/slub.c:2472:1: error: conflicting types for ‘kmem_cache_alloc_node_trace’
  include/linux/slab.h:313:14: note: previous declaration of ‘kmem_cache_alloc_node_trace’ was here

Signed-off-by: Pekka Enberg <penberg@kernel.org>