CHROMIUM: drm/nouveau: pmu: gk20a: Do not use variable before it is set
drivers/gpu/drm/nouveau/nvkm/subdev/pmu/gk20a.c:
	In function 'gk20a_pmu_ctor':
drivers/gpu/drm/nouveau/nvkm/subdev/pmu/gk20a.c:3292:17: error:
	'pmu' may be used uninitialized in this function

Fixes: 5ca1ed831a7b ("drm/nouveau: pmu: add powergating support.")
BUG=chromium:583462
TEST=None (build)

Change-Id: I5c4cea2f058a9da2ae273fe8c8909533dd3043c9
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325480
Reviewed-by: Sean Paul <seanpaul@google.com>