UPSTREAM: rhashtable: fix missing header
Fixup below build error:

include/linux/rhashtable.h: At top level:
include/linux/rhashtable.h:118:34: error: field mutex has incomplete type

Signed-off-by: Ying Xue <ying.xue@windriver.com>
Acked-by: Thomas Graf <tgraf@suug.ch>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from commit 86b35b64ed7b6b38305dee67a0f2ddff2ca5455d)

BUG=chromium:556861
TEST=builds all four kernel flavors based on chromeos-3.18 branch

Change-Id: I9420788b05531c3f6040ac17bdb37cde7b580633
Signed-off-by: Grant Grundler <grundler@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/314146
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>