CHROMIUM: Input: cyapa - bl_enter() takes a little time
On smbus systems, the i2c->smbus fallback in get_state() is backwards when
entering bl.  Avoid dealing with this by delaying get_state() post reset.

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chromium-os:24135
TEST=cyapa_fw_update -b -o /tmp/cyapa.bin
 => should not fail to detect device entering bootloader, like this:
 ERROR: Failed to reset trackpad device, unable switch to firmware
 bootloader idle state, -1.
 WARNING: Failed to open firmware backup file.

Reviewed-on: https://gerrit.chromium.org/gerrit/12811
Reviewed-by: Benson Leung <bleung@chromium.org>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
(cherry picked from commit 8ad90bee6e24e17dff57a3c0403e0d25f6024e01)

Change-Id: I4f452b2932ac316332db37a5348404fa0b541ace
Signed-off-by: Benson Leung <bleung@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/14428
Reviewed-by: Olof Johansson <olofj@chromium.org>