Revert "UPSTREAM: mmc: mediatek: Add Mediatek MMC driver"
This reverts commit 15c01194cea7f30ceccf77cecea75dd37b724073.

Paul Gortmaker <paul.gortmaker@windriver.com> reported on the
mailing list that this commit broke linux-next since it gets
exposed as an implicit module.h user that does not include
module.h:

   drivers/mmc/host/mtk-sd.c:1459:1: note: in expansion of macro
'module_platform_driver'
    module_platform_driver(mt_msdc_driver);
    ^
   include/linux/device.h:1296:1: error: type defaults to 'int' in
declaration of 'module_init' [-Werror=implicit-int]
    module_init(__driver##_init); \
    ^

mmc maintainer Ulf Hansson <ulf.hansson@linaro.org> rebased his
mmc/next branch from which this patch was originally taken.

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chrome-os-partner:38746
TEST=build and boot oak-rev2

Change-Id: Ibe9466c30e3e1e33c73e1cd1b195bbd936cf54df
Reviewed-on: https://chromium-review.googlesource.com/280393
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Trybot-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>