CHROMIUM: md: verity: Make DM_VERITY_CHROMEOS tristate
If DM_VERITY_CHROMEOS is boolean and DM_VERITYis configured as module,
the following build error occurs.

drivers/built-in.o: In function `dm_verity_chromeos_init':
dm-verity-chromeos.c:(.init.text+0x14953):
	undefined reference to `dm_verity_register_error_notifier'
drivers/built-in.o: In function `dm_verity_chromeos_exit':
dm-verity-chromeos.c:(.exit.text+0x955):
	undefined reference to `dm_verity_unregister_error_notifier'

Fixes: fab0fce6e792 ("CHROMIUM: verity: bring over dm-verity-chromeos.c")
BUG=chromium:583462
TEST=None (build)

Change-Id: I5b74993eff2699d0a8ac4459b84dea26b65e3488
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325309
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>