FIXUP: CHROMIUM: Eliminate task stack trace duplication
The original patch only works if CONFIG_STACKTRACE=y

Otherwise, kernel/sched/core.c is compiled with the #else clause in
include/linux/stacktrace.h:

#ifdef CONFIG_STACKTRACE
...
extern unsigned int save_dup_stack_trace(struct task_struct *tsk);
...
#else
...
# define save_dup_stack_trace(tsk)                      do { } while (0)
...
#endif

This causes the following hunk added by that patch to fail to compile for
two reasons.
+		dup_stack_pid = save_dup_stack_trace(p);
+		show_stack_dedup(p, NULL, dup_stack_pid);

(a)
kernel/sched/core.c: In function ‘_sched_show_task’:
kernel/sched/core.c:4560:19: error: expected expression before ‘do’
   dup_stack_pid = save_dup_stack_trace(p);
                   ^
(b)
kernel/sched/core.c:4561: undefined reference to `show_stack_dedup'

These are fixed by updating the #else stubs in
include/linux/stacktrace.h.

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chromium:481177
TEST=Build chromeos-3.18 w/ arm64 defconfig (w/ CONFIG_FTRACE=n):
 1. cd src/third_party/kernel/v3.18
 3. export ARCH=arm64
 4. export CROSS_COMPILE=aarch64-linux-gnu-
 5. make defconfig
 6. make -j32
 => No build breakage in kernel/sched/core.c

Change-Id: Ia47e7772da5ad2a5d627d4bc7f5796c0126d42fb
Reviewed-on: https://chromium-review.googlesource.com/267653
Reviewed-by: Sameer Nanda <snanda@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Trybot-Ready: Daniel Kurtz <djkurtz@chromium.org>