CHROMIUM: drm: imx208: Drop MODULE_DEVICE_TABLE
If built as module, compilation fails with

include/linux/module.h:138:40: error: '__mod_of__imx208_of_match_device_table'
aliased to undefined symbol 'imx208_of_match'
drivers/gpu/drm/tegra/camera/imx208.c:637:1: note:
	in expansion of macro 'MODULE_DEVICE_TABLE'
	MODULE_DEVICE_TABLE(of, imx208_of_match);

Fixes: b4ebe6d12cfe ("CHROMIUM: tegra/drm: Add IMX208 driver")
BUG=chromium:583462
TEST=None (build)

Change-Id: I7af0070ee8901629adf98e9613941c361927ea35
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325408
Reviewed-by: Sean Paul <seanpaul@google.com>