CHROMIUM: usb: dwc: Fix ARM usb_phy init parameter warning
Adding the param "bool ext_clk" to phy_init() results in some warnings:

arch/arm/mach-exynos/mach-exynos5-dt.c:535:2: error: initialization from
incompatible pointer type [-Werror]
arch/arm/mach-exynos/mach-exynos5-dt.c:540:2: error: initialization from
incompatible pointer type [-Werror]

Instead of updating this function pointer to have the extra variable,
add a new function to set "ext_clk" as a static variable in
setup-usb-phy.c

BUG=chromium-os:5542
TEST=emerge-daisy chromeos-kernel, make sure warning is gone

Change-Id: Ic2c38acd945083b0509dafe9dadf12935868991d
Signed-off-by: Simon Que <sque@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/42367
Reviewed-by: Vincent Palatin <vpalatin@chromium.org>