Revert "UPSTREAM: ALSA: HDA: Jack: Export required functions from hda_jack.c"
This reverts commit afd43b519b60af27fec28e020e4f99270d893a1a

The x86/amd64 kernel builds are broken:

ERROR: "snd_hda_jack_add_kctl" [sound/pci/hda/snd-hda-codec-hdmi.ko] undefined

http://build.chromium.org/p/chromiumos/builders/amd64%20generic%20full/builds/2165/steps/cbuildbot/logs/stdio
Change-Id: I781d8b5cf2527ed878fab0f531b1fe36ce2ab1f0
Reviewed-on: https://gerrit.chromium.org/gerrit/21314
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>