FIXUP: CHROMIUM: PM / wakeup: add tracking platform wakeup source
The wakeup_type names are only defined if CONFIG_PM_RUNTIME is defined.
Thus, we must guard the inclusiona and implementation of the wakeup_type
sysfs entry as well.

This fixes these build errors when CONFIG_PM_RUNTIME is not defined:
drivers/base/power/sysfs.c: In function 'wakeup_type_show':
drivers/base/power/sysfs.c:522:31: error: 'unknown' undeclared (first use in this function)
   return sprintf(buf, "%s\n", unknown);
                               ^
drivers/base/power/sysfs.c:522:31: note: each undeclared identifier is reported only once for each function it appears in

drivers/base/power/sysfs.c:524:31: error: 'automatic' undeclared (first use in this function)
   return sprintf(buf, "%s\n", automatic);
                               ^
drivers/base/power/sysfs.c:526:31: error: 'user' undeclared (first use in this function)
   return sprintf(buf, "%s\n", user);
                               ^
drivers/base/power/sysfs.c:528:31: error: 'invalid' undeclared (first use in this function)
   return sprintf(buf, "%s\n", invalid);
                               ^
drivers/base/power/sysfs.c: In function 'wakeup_type_store':
drivers/base/power/sysfs.c:538:18: error: 'unknown' undeclared (first use in this function)
  if (sysfs_streq(unknown, buf))
                  ^
drivers/base/power/sysfs.c:540:23: error: 'automatic' undeclared (first use in this function)
  else if (sysfs_streq(automatic, buf))
                       ^
drivers/base/power/sysfs.c:542:23: error: 'user' undeclared (first use in this function)
  else if (sysfs_streq(user, buf))
                       ^
drivers/base/power/sysfs.c: In function 'wakeup_type_show':

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chrome-os-partner:38563
TEST=emerge-oak chromeos-kernel-3_18

Change-Id: Ia4da3756dcb8f645a49579f42ef576576c3ad881