UPSTREAM: nios2: add definition of ioremap_wc to io.h
Fix

drivers/gpu/drm/drm_bufs.c: In function 'drm_addmap_core':
drivers/gpu/drm/drm_bufs.c:213:5:
			error: implicit declaration of function 'ioremap_wc'

seen when building nios2:allmodconfig.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Acked-by: Ley Foon Tan <lftan@altera.com>
(cherry picked from commit 76367a52d3cbf78f254fee0479824014c8dfb4dc)
Signed-off-by: Andrew-CT Chen <andrew-ct.chen@mediatek.com>

TEST=build and boot oak-rev3
BUG=chrome-os-partner:49541

Change-Id: I217270c76b1d4664f39002fddfe219b2a8ac32da
Reviewed-on: https://chromium-review.googlesource.com/322587
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>