UPSTREAM: ASoC: rt5677: add build dependency to spi
Since 9cb715a9d4c the codec has a hardcoded dependency to spi.
Add this dependency to Kconfig. It fixes buildbot compilation failure:

   sound/built-in.o: In function `spi_write':
>> rt5677-spi.c:(.text+0x8265f): undefined reference to `spi_sync'
   sound/built-in.o: In function `rt5677_spi_driver_init':
>> rt5677-spi.c:(.init.text+0x17db): undefined reference to `spi_register_driver'

Signed-off-by: Anatol Pomozov <anatol.pomozov@gmail.com>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit ac884fc47b7750b1e7eaf04f0236610c84ceee54)

Signed-off-by: Koro Chen <koro.chen@mediatek.com>

BUG=chrome-os-partner:38746
TEST=build and boot oak-rev0

Change-Id: I62d49004e693d6b24db4a4b3697a9aa95a8d7201
Reviewed-on: https://chromium-review.googlesource.com/269024
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Trybot-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>